/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.datastealth;


import org.apache.thrift.TEnum;

public enum IndexEntryStatus implements TEnum {
  FLTTOL(1),
  DGRDED(2),
  CRITCL(4),
  NONCMP(8),
  FAILED(16),
  OBSLTE(32),
  DELETED(64),
  PURGED(128);

  private final int value;

  private IndexEntryStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static IndexEntryStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return FLTTOL;
      case 2:
        return DGRDED;
      case 4:
        return CRITCL;
      case 8:
        return NONCMP;
      case 16:
        return FAILED;
      case 32:
        return OBSLTE;
      case 64:
        return DELETED;
      case 128:
        return PURGED;
      default:
        return null;
    }
  }
}
