/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.datastealth;

import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.nio.ByteBuffer;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class IndexEntry implements org.apache.thrift.TBase<IndexEntry, IndexEntry._Fields>, java.io.Serializable, Cloneable, Comparable<IndexEntry> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IndexEntry");

  private static final org.apache.thrift.protocol.TField UNIQUE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("uniqueId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField VAULT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("vaultId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OWNER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ownerId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("token", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField UPDATE_TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("updateTimestamp", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField ALTERNATE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("alternateId", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField ENTRY_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("entryData", org.apache.thrift.protocol.TType.STRING, (short)20);
  private static final org.apache.thrift.protocol.TField META_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("metaData", org.apache.thrift.protocol.TType.MAP, (short)30);
  private static final org.apache.thrift.protocol.TField CODEC_STRING_FIELD_DESC = new org.apache.thrift.protocol.TField("codecString", org.apache.thrift.protocol.TType.STRING, (short)40);
  private static final org.apache.thrift.protocol.TField DISPERSAL_ALGORITHM_FIELD_DESC = new org.apache.thrift.protocol.TField("dispersalAlgorithm", org.apache.thrift.protocol.TType.STRING, (short)41);
  private static final org.apache.thrift.protocol.TField FRAGMENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("fragmentId", org.apache.thrift.protocol.TType.STRING, (short)42);
  private static final org.apache.thrift.protocol.TField FRAGMENT_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("fragmentCount", org.apache.thrift.protocol.TType.I16, (short)43);
  private static final org.apache.thrift.protocol.TField STORAGE_NODE_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("storageNodeMap", org.apache.thrift.protocol.TType.LIST, (short)44);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new IndexEntryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new IndexEntryTupleSchemeFactory());
  }

  public String uniqueId; // required
  public String vaultId; // required
  public String ownerId; // required
  public String token; // required
  public long timestamp; // required
  public long updateTimestamp; // required
  /**
   * 
   * @see IndexEntryStatus
   */
  public IndexEntryStatus status; // required
  public String alternateId; // optional
  public ByteBuffer entryData; // optional
  public Map<String,String> metaData; // optional
  public String codecString; // required
  public String dispersalAlgorithm; // required
  public ByteBuffer fragmentId; // required
  public short fragmentCount; // required
  public List<Integer> storageNodeMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UNIQUE_ID((short)1, "uniqueId"),
    VAULT_ID((short)2, "vaultId"),
    OWNER_ID((short)3, "ownerId"),
    TOKEN((short)4, "token"),
    TIMESTAMP((short)6, "timestamp"),
    UPDATE_TIMESTAMP((short)7, "updateTimestamp"),
    /**
     * 
     * @see IndexEntryStatus
     */
    STATUS((short)9, "status"),
    ALTERNATE_ID((short)10, "alternateId"),
    ENTRY_DATA((short)20, "entryData"),
    META_DATA((short)30, "metaData"),
    CODEC_STRING((short)40, "codecString"),
    DISPERSAL_ALGORITHM((short)41, "dispersalAlgorithm"),
    FRAGMENT_ID((short)42, "fragmentId"),
    FRAGMENT_COUNT((short)43, "fragmentCount"),
    STORAGE_NODE_MAP((short)44, "storageNodeMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UNIQUE_ID
          return UNIQUE_ID;
        case 2: // VAULT_ID
          return VAULT_ID;
        case 3: // OWNER_ID
          return OWNER_ID;
        case 4: // TOKEN
          return TOKEN;
        case 6: // TIMESTAMP
          return TIMESTAMP;
        case 7: // UPDATE_TIMESTAMP
          return UPDATE_TIMESTAMP;
        case 9: // STATUS
          return STATUS;
        case 10: // ALTERNATE_ID
          return ALTERNATE_ID;
        case 20: // ENTRY_DATA
          return ENTRY_DATA;
        case 30: // META_DATA
          return META_DATA;
        case 40: // CODEC_STRING
          return CODEC_STRING;
        case 41: // DISPERSAL_ALGORITHM
          return DISPERSAL_ALGORITHM;
        case 42: // FRAGMENT_ID
          return FRAGMENT_ID;
        case 43: // FRAGMENT_COUNT
          return FRAGMENT_COUNT;
        case 44: // STORAGE_NODE_MAP
          return STORAGE_NODE_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMP_ISSET_ID = 0;
  private static final int __UPDATETIMESTAMP_ISSET_ID = 1;
  private static final int __FRAGMENTCOUNT_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.ALTERNATE_ID, _Fields.ENTRY_DATA, _Fields.META_DATA};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UNIQUE_ID, new org.apache.thrift.meta_data.FieldMetaData("uniqueId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VAULT_ID, new org.apache.thrift.meta_data.FieldMetaData("vaultId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OWNER_ID, new org.apache.thrift.meta_data.FieldMetaData("ownerId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TOKEN, new org.apache.thrift.meta_data.FieldMetaData("token", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.UPDATE_TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("updateTimestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, IndexEntryStatus.class)));
    tmpMap.put(_Fields.ALTERNATE_ID, new org.apache.thrift.meta_data.FieldMetaData("alternateId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENTRY_DATA, new org.apache.thrift.meta_data.FieldMetaData("entryData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.META_DATA, new org.apache.thrift.meta_data.FieldMetaData("metaData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.CODEC_STRING, new org.apache.thrift.meta_data.FieldMetaData("codecString", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISPERSAL_ALGORITHM, new org.apache.thrift.meta_data.FieldMetaData("dispersalAlgorithm", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FRAGMENT_ID, new org.apache.thrift.meta_data.FieldMetaData("fragmentId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.FRAGMENT_COUNT, new org.apache.thrift.meta_data.FieldMetaData("fragmentCount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.STORAGE_NODE_MAP, new org.apache.thrift.meta_data.FieldMetaData("storageNodeMap", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IndexEntry.class, metaDataMap);
  }

  public IndexEntry() {
  }

  public IndexEntry(
    String uniqueId,
    String vaultId,
    String ownerId,
    String token,
    long timestamp,
    long updateTimestamp,
    IndexEntryStatus status,
    String codecString,
    String dispersalAlgorithm,
    ByteBuffer fragmentId,
    short fragmentCount,
    List<Integer> storageNodeMap)
  {
    this();
    this.uniqueId = uniqueId;
    this.vaultId = vaultId;
    this.ownerId = ownerId;
    this.token = token;
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    this.updateTimestamp = updateTimestamp;
    setUpdateTimestampIsSet(true);
    this.status = status;
    this.codecString = codecString;
    this.dispersalAlgorithm = dispersalAlgorithm;
    this.fragmentId = org.apache.thrift.TBaseHelper.copyBinary(fragmentId);
    this.fragmentCount = fragmentCount;
    setFragmentCountIsSet(true);
    this.storageNodeMap = storageNodeMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IndexEntry(IndexEntry other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetUniqueId()) {
      this.uniqueId = other.uniqueId;
    }
    if (other.isSetVaultId()) {
      this.vaultId = other.vaultId;
    }
    if (other.isSetOwnerId()) {
      this.ownerId = other.ownerId;
    }
    if (other.isSetToken()) {
      this.token = other.token;
    }
    this.timestamp = other.timestamp;
    this.updateTimestamp = other.updateTimestamp;
    if (other.isSetStatus()) {
      this.status = other.status;
    }
    if (other.isSetAlternateId()) {
      this.alternateId = other.alternateId;
    }
    if (other.isSetEntryData()) {
      this.entryData = org.apache.thrift.TBaseHelper.copyBinary(other.entryData);
    }
    if (other.isSetMetaData()) {
      Map<String,String> __this__metaData = new HashMap<String,String>(other.metaData);
      this.metaData = __this__metaData;
    }
    if (other.isSetCodecString()) {
      this.codecString = other.codecString;
    }
    if (other.isSetDispersalAlgorithm()) {
      this.dispersalAlgorithm = other.dispersalAlgorithm;
    }
    if (other.isSetFragmentId()) {
      this.fragmentId = org.apache.thrift.TBaseHelper.copyBinary(other.fragmentId);
    }
    this.fragmentCount = other.fragmentCount;
    if (other.isSetStorageNodeMap()) {
      List<Integer> __this__storageNodeMap = new ArrayList<Integer>(other.storageNodeMap);
      this.storageNodeMap = __this__storageNodeMap;
    }
  }

  public IndexEntry deepCopy() {
    return new IndexEntry(this);
  }

  @Override
  public void clear() {
    this.uniqueId = null;
    this.vaultId = null;
    this.ownerId = null;
    this.token = null;
    setTimestampIsSet(false);
    this.timestamp = 0;
    setUpdateTimestampIsSet(false);
    this.updateTimestamp = 0;
    this.status = null;
    this.alternateId = null;
    this.entryData = null;
    this.metaData = null;
    this.codecString = null;
    this.dispersalAlgorithm = null;
    this.fragmentId = null;
    setFragmentCountIsSet(false);
    this.fragmentCount = 0;
    this.storageNodeMap = null;
  }

  public String getUniqueId() {
    return this.uniqueId;
  }

  public IndexEntry setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

  public void unsetUniqueId() {
    this.uniqueId = null;
  }

  /** Returns true if field uniqueId is set (has been assigned a value) and false otherwise */
  public boolean isSetUniqueId() {
    return this.uniqueId != null;
  }

  public void setUniqueIdIsSet(boolean value) {
    if (!value) {
      this.uniqueId = null;
    }
  }

  public String getVaultId() {
    return this.vaultId;
  }

  public IndexEntry setVaultId(String vaultId) {
    this.vaultId = vaultId;
    return this;
  }

  public void unsetVaultId() {
    this.vaultId = null;
  }

  /** Returns true if field vaultId is set (has been assigned a value) and false otherwise */
  public boolean isSetVaultId() {
    return this.vaultId != null;
  }

  public void setVaultIdIsSet(boolean value) {
    if (!value) {
      this.vaultId = null;
    }
  }

  public String getOwnerId() {
    return this.ownerId;
  }

  public IndexEntry setOwnerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  public void unsetOwnerId() {
    this.ownerId = null;
  }

  /** Returns true if field ownerId is set (has been assigned a value) and false otherwise */
  public boolean isSetOwnerId() {
    return this.ownerId != null;
  }

  public void setOwnerIdIsSet(boolean value) {
    if (!value) {
      this.ownerId = null;
    }
  }

  public String getToken() {
    return this.token;
  }

  public IndexEntry setToken(String token) {
    this.token = token;
    return this;
  }

  public void unsetToken() {
    this.token = null;
  }

  /** Returns true if field token is set (has been assigned a value) and false otherwise */
  public boolean isSetToken() {
    return this.token != null;
  }

  public void setTokenIsSet(boolean value) {
    if (!value) {
      this.token = null;
    }
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public IndexEntry setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public long getUpdateTimestamp() {
    return this.updateTimestamp;
  }

  public IndexEntry setUpdateTimestamp(long updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
    setUpdateTimestampIsSet(true);
    return this;
  }

  public void unsetUpdateTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UPDATETIMESTAMP_ISSET_ID);
  }

  /** Returns true if field updateTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdateTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __UPDATETIMESTAMP_ISSET_ID);
  }

  public void setUpdateTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UPDATETIMESTAMP_ISSET_ID, value);
  }

  /**
   * 
   * @see IndexEntryStatus
   */
  public IndexEntryStatus getStatus() {
    return this.status;
  }

  /**
   * 
   * @see IndexEntryStatus
   */
  public IndexEntry setStatus(IndexEntryStatus status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public String getAlternateId() {
    return this.alternateId;
  }

  public IndexEntry setAlternateId(String alternateId) {
    this.alternateId = alternateId;
    return this;
  }

  public void unsetAlternateId() {
    this.alternateId = null;
  }

  /** Returns true if field alternateId is set (has been assigned a value) and false otherwise */
  public boolean isSetAlternateId() {
    return this.alternateId != null;
  }

  public void setAlternateIdIsSet(boolean value) {
    if (!value) {
      this.alternateId = null;
    }
  }

  public byte[] getEntryData() {
    setEntryData(org.apache.thrift.TBaseHelper.rightSize(entryData));
    return entryData == null ? null : entryData.array();
  }

  public ByteBuffer bufferForEntryData() {
    return org.apache.thrift.TBaseHelper.copyBinary(entryData);
  }

  public IndexEntry setEntryData(byte[] entryData) {
    this.entryData = entryData == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(entryData, entryData.length));
    return this;
  }

  public IndexEntry setEntryData(ByteBuffer entryData) {
    this.entryData = org.apache.thrift.TBaseHelper.copyBinary(entryData);
    return this;
  }

  public void unsetEntryData() {
    this.entryData = null;
  }

  /** Returns true if field entryData is set (has been assigned a value) and false otherwise */
  public boolean isSetEntryData() {
    return this.entryData != null;
  }

  public void setEntryDataIsSet(boolean value) {
    if (!value) {
      this.entryData = null;
    }
  }

  public int getMetaDataSize() {
    return (this.metaData == null) ? 0 : this.metaData.size();
  }

  public void putToMetaData(String key, String val) {
    if (this.metaData == null) {
      this.metaData = new HashMap<String,String>();
    }
    this.metaData.put(key, val);
  }

  public Map<String,String> getMetaData() {
    return this.metaData;
  }

  public IndexEntry setMetaData(Map<String,String> metaData) {
    this.metaData = metaData;
    return this;
  }

  public void unsetMetaData() {
    this.metaData = null;
  }

  /** Returns true if field metaData is set (has been assigned a value) and false otherwise */
  public boolean isSetMetaData() {
    return this.metaData != null;
  }

  public void setMetaDataIsSet(boolean value) {
    if (!value) {
      this.metaData = null;
    }
  }

  public String getCodecString() {
    return this.codecString;
  }

  public IndexEntry setCodecString(String codecString) {
    this.codecString = codecString;
    return this;
  }

  public void unsetCodecString() {
    this.codecString = null;
  }

  /** Returns true if field codecString is set (has been assigned a value) and false otherwise */
  public boolean isSetCodecString() {
    return this.codecString != null;
  }

  public void setCodecStringIsSet(boolean value) {
    if (!value) {
      this.codecString = null;
    }
  }

  public String getDispersalAlgorithm() {
    return this.dispersalAlgorithm;
  }

  public IndexEntry setDispersalAlgorithm(String dispersalAlgorithm) {
    this.dispersalAlgorithm = dispersalAlgorithm;
    return this;
  }

  public void unsetDispersalAlgorithm() {
    this.dispersalAlgorithm = null;
  }

  /** Returns true if field dispersalAlgorithm is set (has been assigned a value) and false otherwise */
  public boolean isSetDispersalAlgorithm() {
    return this.dispersalAlgorithm != null;
  }

  public void setDispersalAlgorithmIsSet(boolean value) {
    if (!value) {
      this.dispersalAlgorithm = null;
    }
  }

  public byte[] getFragmentId() {
    setFragmentId(org.apache.thrift.TBaseHelper.rightSize(fragmentId));
    return fragmentId == null ? null : fragmentId.array();
  }

  public ByteBuffer bufferForFragmentId() {
    return org.apache.thrift.TBaseHelper.copyBinary(fragmentId);
  }

  public IndexEntry setFragmentId(byte[] fragmentId) {
    this.fragmentId = fragmentId == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(fragmentId, fragmentId.length));
    return this;
  }

  public IndexEntry setFragmentId(ByteBuffer fragmentId) {
    this.fragmentId = org.apache.thrift.TBaseHelper.copyBinary(fragmentId);
    return this;
  }

  public void unsetFragmentId() {
    this.fragmentId = null;
  }

  /** Returns true if field fragmentId is set (has been assigned a value) and false otherwise */
  public boolean isSetFragmentId() {
    return this.fragmentId != null;
  }

  public void setFragmentIdIsSet(boolean value) {
    if (!value) {
      this.fragmentId = null;
    }
  }

  public short getFragmentCount() {
    return this.fragmentCount;
  }

  public IndexEntry setFragmentCount(short fragmentCount) {
    this.fragmentCount = fragmentCount;
    setFragmentCountIsSet(true);
    return this;
  }

  public void unsetFragmentCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FRAGMENTCOUNT_ISSET_ID);
  }

  /** Returns true if field fragmentCount is set (has been assigned a value) and false otherwise */
  public boolean isSetFragmentCount() {
    return EncodingUtils.testBit(__isset_bitfield, __FRAGMENTCOUNT_ISSET_ID);
  }

  public void setFragmentCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FRAGMENTCOUNT_ISSET_ID, value);
  }

  public int getStorageNodeMapSize() {
    return (this.storageNodeMap == null) ? 0 : this.storageNodeMap.size();
  }

  public java.util.Iterator<Integer> getStorageNodeMapIterator() {
    return (this.storageNodeMap == null) ? null : this.storageNodeMap.iterator();
  }

  public void addToStorageNodeMap(int elem) {
    if (this.storageNodeMap == null) {
      this.storageNodeMap = new ArrayList<Integer>();
    }
    this.storageNodeMap.add(elem);
  }

  public List<Integer> getStorageNodeMap() {
    return this.storageNodeMap;
  }

  public IndexEntry setStorageNodeMap(List<Integer> storageNodeMap) {
    this.storageNodeMap = storageNodeMap;
    return this;
  }

  public void unsetStorageNodeMap() {
    this.storageNodeMap = null;
  }

  /** Returns true if field storageNodeMap is set (has been assigned a value) and false otherwise */
  public boolean isSetStorageNodeMap() {
    return this.storageNodeMap != null;
  }

  public void setStorageNodeMapIsSet(boolean value) {
    if (!value) {
      this.storageNodeMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UNIQUE_ID:
      if (value == null) {
        unsetUniqueId();
      } else {
        setUniqueId((String)value);
      }
      break;

    case VAULT_ID:
      if (value == null) {
        unsetVaultId();
      } else {
        setVaultId((String)value);
      }
      break;

    case OWNER_ID:
      if (value == null) {
        unsetOwnerId();
      } else {
        setOwnerId((String)value);
      }
      break;

    case TOKEN:
      if (value == null) {
        unsetToken();
      } else {
        setToken((String)value);
      }
      break;

    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((Long)value);
      }
      break;

    case UPDATE_TIMESTAMP:
      if (value == null) {
        unsetUpdateTimestamp();
      } else {
        setUpdateTimestamp((Long)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((IndexEntryStatus)value);
      }
      break;

    case ALTERNATE_ID:
      if (value == null) {
        unsetAlternateId();
      } else {
        setAlternateId((String)value);
      }
      break;

    case ENTRY_DATA:
      if (value == null) {
        unsetEntryData();
      } else {
        setEntryData((ByteBuffer)value);
      }
      break;

    case META_DATA:
      if (value == null) {
        unsetMetaData();
      } else {
        setMetaData((Map<String,String>)value);
      }
      break;

    case CODEC_STRING:
      if (value == null) {
        unsetCodecString();
      } else {
        setCodecString((String)value);
      }
      break;

    case DISPERSAL_ALGORITHM:
      if (value == null) {
        unsetDispersalAlgorithm();
      } else {
        setDispersalAlgorithm((String)value);
      }
      break;

    case FRAGMENT_ID:
      if (value == null) {
        unsetFragmentId();
      } else {
        setFragmentId((ByteBuffer)value);
      }
      break;

    case FRAGMENT_COUNT:
      if (value == null) {
        unsetFragmentCount();
      } else {
        setFragmentCount((Short)value);
      }
      break;

    case STORAGE_NODE_MAP:
      if (value == null) {
        unsetStorageNodeMap();
      } else {
        setStorageNodeMap((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UNIQUE_ID:
      return getUniqueId();

    case VAULT_ID:
      return getVaultId();

    case OWNER_ID:
      return getOwnerId();

    case TOKEN:
      return getToken();

    case TIMESTAMP:
      return getTimestamp();

    case UPDATE_TIMESTAMP:
      return getUpdateTimestamp();

    case STATUS:
      return getStatus();

    case ALTERNATE_ID:
      return getAlternateId();

    case ENTRY_DATA:
      return getEntryData();

    case META_DATA:
      return getMetaData();

    case CODEC_STRING:
      return getCodecString();

    case DISPERSAL_ALGORITHM:
      return getDispersalAlgorithm();

    case FRAGMENT_ID:
      return getFragmentId();

    case FRAGMENT_COUNT:
      return getFragmentCount();

    case STORAGE_NODE_MAP:
      return getStorageNodeMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case UNIQUE_ID:
      return isSetUniqueId();
    case VAULT_ID:
      return isSetVaultId();
    case OWNER_ID:
      return isSetOwnerId();
    case TOKEN:
      return isSetToken();
    case TIMESTAMP:
      return isSetTimestamp();
    case UPDATE_TIMESTAMP:
      return isSetUpdateTimestamp();
    case STATUS:
      return isSetStatus();
    case ALTERNATE_ID:
      return isSetAlternateId();
    case ENTRY_DATA:
      return isSetEntryData();
    case META_DATA:
      return isSetMetaData();
    case CODEC_STRING:
      return isSetCodecString();
    case DISPERSAL_ALGORITHM:
      return isSetDispersalAlgorithm();
    case FRAGMENT_ID:
      return isSetFragmentId();
    case FRAGMENT_COUNT:
      return isSetFragmentCount();
    case STORAGE_NODE_MAP:
      return isSetStorageNodeMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IndexEntry)
      return this.equals((IndexEntry)that);
    return false;
  }

  public boolean equals(IndexEntry that) {
    if (that == null)
      return false;

    boolean this_present_uniqueId = true && this.isSetUniqueId();
    boolean that_present_uniqueId = true && that.isSetUniqueId();
    if (this_present_uniqueId || that_present_uniqueId) {
      if (!(this_present_uniqueId && that_present_uniqueId))
        return false;
      if (!this.uniqueId.equals(that.uniqueId))
        return false;
    }

    boolean this_present_vaultId = true && this.isSetVaultId();
    boolean that_present_vaultId = true && that.isSetVaultId();
    if (this_present_vaultId || that_present_vaultId) {
      if (!(this_present_vaultId && that_present_vaultId))
        return false;
      if (!this.vaultId.equals(that.vaultId))
        return false;
    }

    boolean this_present_ownerId = true && this.isSetOwnerId();
    boolean that_present_ownerId = true && that.isSetOwnerId();
    if (this_present_ownerId || that_present_ownerId) {
      if (!(this_present_ownerId && that_present_ownerId))
        return false;
      if (!this.ownerId.equals(that.ownerId))
        return false;
    }

    boolean this_present_token = true && this.isSetToken();
    boolean that_present_token = true && that.isSetToken();
    if (this_present_token || that_present_token) {
      if (!(this_present_token && that_present_token))
        return false;
      if (!this.token.equals(that.token))
        return false;
    }

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    boolean this_present_updateTimestamp = true;
    boolean that_present_updateTimestamp = true;
    if (this_present_updateTimestamp || that_present_updateTimestamp) {
      if (!(this_present_updateTimestamp && that_present_updateTimestamp))
        return false;
      if (this.updateTimestamp != that.updateTimestamp)
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_alternateId = true && this.isSetAlternateId();
    boolean that_present_alternateId = true && that.isSetAlternateId();
    if (this_present_alternateId || that_present_alternateId) {
      if (!(this_present_alternateId && that_present_alternateId))
        return false;
      if (!this.alternateId.equals(that.alternateId))
        return false;
    }

    boolean this_present_entryData = true && this.isSetEntryData();
    boolean that_present_entryData = true && that.isSetEntryData();
    if (this_present_entryData || that_present_entryData) {
      if (!(this_present_entryData && that_present_entryData))
        return false;
      if (!this.entryData.equals(that.entryData))
        return false;
    }

    boolean this_present_metaData = true && this.isSetMetaData();
    boolean that_present_metaData = true && that.isSetMetaData();
    if (this_present_metaData || that_present_metaData) {
      if (!(this_present_metaData && that_present_metaData))
        return false;
      if (!this.metaData.equals(that.metaData))
        return false;
    }

    boolean this_present_codecString = true && this.isSetCodecString();
    boolean that_present_codecString = true && that.isSetCodecString();
    if (this_present_codecString || that_present_codecString) {
      if (!(this_present_codecString && that_present_codecString))
        return false;
      if (!this.codecString.equals(that.codecString))
        return false;
    }

    boolean this_present_dispersalAlgorithm = true && this.isSetDispersalAlgorithm();
    boolean that_present_dispersalAlgorithm = true && that.isSetDispersalAlgorithm();
    if (this_present_dispersalAlgorithm || that_present_dispersalAlgorithm) {
      if (!(this_present_dispersalAlgorithm && that_present_dispersalAlgorithm))
        return false;
      if (!this.dispersalAlgorithm.equals(that.dispersalAlgorithm))
        return false;
    }

    boolean this_present_fragmentId = true && this.isSetFragmentId();
    boolean that_present_fragmentId = true && that.isSetFragmentId();
    if (this_present_fragmentId || that_present_fragmentId) {
      if (!(this_present_fragmentId && that_present_fragmentId))
        return false;
      if (!this.fragmentId.equals(that.fragmentId))
        return false;
    }

    boolean this_present_fragmentCount = true;
    boolean that_present_fragmentCount = true;
    if (this_present_fragmentCount || that_present_fragmentCount) {
      if (!(this_present_fragmentCount && that_present_fragmentCount))
        return false;
      if (this.fragmentCount != that.fragmentCount)
        return false;
    }

    boolean this_present_storageNodeMap = true && this.isSetStorageNodeMap();
    boolean that_present_storageNodeMap = true && that.isSetStorageNodeMap();
    if (this_present_storageNodeMap || that_present_storageNodeMap) {
      if (!(this_present_storageNodeMap && that_present_storageNodeMap))
        return false;
      if (!this.storageNodeMap.equals(that.storageNodeMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_uniqueId = true && (isSetUniqueId());
    list.add(present_uniqueId);
    if (present_uniqueId)
      list.add(uniqueId);

    boolean present_vaultId = true && (isSetVaultId());
    list.add(present_vaultId);
    if (present_vaultId)
      list.add(vaultId);

    boolean present_ownerId = true && (isSetOwnerId());
    list.add(present_ownerId);
    if (present_ownerId)
      list.add(ownerId);

    boolean present_token = true && (isSetToken());
    list.add(present_token);
    if (present_token)
      list.add(token);

    boolean present_timestamp = true;
    list.add(present_timestamp);
    if (present_timestamp)
      list.add(timestamp);

    boolean present_updateTimestamp = true;
    list.add(present_updateTimestamp);
    if (present_updateTimestamp)
      list.add(updateTimestamp);

    boolean present_status = true && (isSetStatus());
    list.add(present_status);
    if (present_status)
      list.add(status.getValue());

    boolean present_alternateId = true && (isSetAlternateId());
    list.add(present_alternateId);
    if (present_alternateId)
      list.add(alternateId);

    boolean present_entryData = true && (isSetEntryData());
    list.add(present_entryData);
    if (present_entryData)
      list.add(entryData);

    boolean present_metaData = true && (isSetMetaData());
    list.add(present_metaData);
    if (present_metaData)
      list.add(metaData);

    boolean present_codecString = true && (isSetCodecString());
    list.add(present_codecString);
    if (present_codecString)
      list.add(codecString);

    boolean present_dispersalAlgorithm = true && (isSetDispersalAlgorithm());
    list.add(present_dispersalAlgorithm);
    if (present_dispersalAlgorithm)
      list.add(dispersalAlgorithm);

    boolean present_fragmentId = true && (isSetFragmentId());
    list.add(present_fragmentId);
    if (present_fragmentId)
      list.add(fragmentId);

    boolean present_fragmentCount = true;
    list.add(present_fragmentCount);
    if (present_fragmentCount)
      list.add(fragmentCount);

    boolean present_storageNodeMap = true && (isSetStorageNodeMap());
    list.add(present_storageNodeMap);
    if (present_storageNodeMap)
      list.add(storageNodeMap);

    return list.hashCode();
  }

  @Override
  public int compareTo(IndexEntry other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUniqueId()).compareTo(other.isSetUniqueId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUniqueId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uniqueId, other.uniqueId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVaultId()).compareTo(other.isSetVaultId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVaultId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vaultId, other.vaultId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOwnerId()).compareTo(other.isSetOwnerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwnerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ownerId, other.ownerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetToken()).compareTo(other.isSetToken());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToken()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.token, other.token);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUpdateTimestamp()).compareTo(other.isSetUpdateTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdateTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updateTimestamp, other.updateTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAlternateId()).compareTo(other.isSetAlternateId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAlternateId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alternateId, other.alternateId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEntryData()).compareTo(other.isSetEntryData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEntryData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.entryData, other.entryData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMetaData()).compareTo(other.isSetMetaData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetaData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metaData, other.metaData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCodecString()).compareTo(other.isSetCodecString());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCodecString()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.codecString, other.codecString);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDispersalAlgorithm()).compareTo(other.isSetDispersalAlgorithm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDispersalAlgorithm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dispersalAlgorithm, other.dispersalAlgorithm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFragmentId()).compareTo(other.isSetFragmentId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFragmentId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fragmentId, other.fragmentId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFragmentCount()).compareTo(other.isSetFragmentCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFragmentCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fragmentCount, other.fragmentCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStorageNodeMap()).compareTo(other.isSetStorageNodeMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStorageNodeMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.storageNodeMap, other.storageNodeMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IndexEntry(");
    boolean first = true;

    sb.append("uniqueId:");
    if (this.uniqueId == null) {
      sb.append("null");
    } else {
      sb.append(this.uniqueId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("vaultId:");
    if (this.vaultId == null) {
      sb.append("null");
    } else {
      sb.append(this.vaultId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ownerId:");
    if (this.ownerId == null) {
      sb.append("null");
    } else {
      sb.append(this.ownerId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("token:");
    if (this.token == null) {
      sb.append("null");
    } else {
      sb.append(this.token);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("updateTimestamp:");
    sb.append(this.updateTimestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    if (isSetAlternateId()) {
      if (!first) sb.append(", ");
      sb.append("alternateId:");
      if (this.alternateId == null) {
        sb.append("null");
      } else {
        sb.append(this.alternateId);
      }
      first = false;
    }
    if (isSetEntryData()) {
      if (!first) sb.append(", ");
      sb.append("entryData:");
      if (this.entryData == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.entryData, sb);
      }
      first = false;
    }
    if (isSetMetaData()) {
      if (!first) sb.append(", ");
      sb.append("metaData:");
      if (this.metaData == null) {
        sb.append("null");
      } else {
        sb.append(this.metaData);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("codecString:");
    if (this.codecString == null) {
      sb.append("null");
    } else {
      sb.append(this.codecString);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dispersalAlgorithm:");
    if (this.dispersalAlgorithm == null) {
      sb.append("null");
    } else {
      sb.append(this.dispersalAlgorithm);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fragmentId:");
    if (this.fragmentId == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.fragmentId, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fragmentCount:");
    sb.append(this.fragmentCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("storageNodeMap:");
    if (this.storageNodeMap == null) {
      sb.append("null");
    } else {
      sb.append(this.storageNodeMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (uniqueId == null) {
      throw new TProtocolException("Required field 'uniqueId' was not present! Struct: " + toString());
    }
    if (vaultId == null) {
      throw new TProtocolException("Required field 'vaultId' was not present! Struct: " + toString());
    }
    if (ownerId == null) {
      throw new TProtocolException("Required field 'ownerId' was not present! Struct: " + toString());
    }
    if (token == null) {
      throw new TProtocolException("Required field 'token' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'timestamp' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'updateTimestamp' because it's a primitive and you chose the non-beans generator.
    if (status == null) {
      throw new TProtocolException("Required field 'status' was not present! Struct: " + toString());
    }
    if (codecString == null) {
      throw new TProtocolException("Required field 'codecString' was not present! Struct: " + toString());
    }
    if (dispersalAlgorithm == null) {
      throw new TProtocolException("Required field 'dispersalAlgorithm' was not present! Struct: " + toString());
    }
    if (fragmentId == null) {
      throw new TProtocolException("Required field 'fragmentId' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'fragmentCount' because it's a primitive and you chose the non-beans generator.
    if (storageNodeMap == null) {
      throw new TProtocolException("Required field 'storageNodeMap' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IndexEntryStandardSchemeFactory implements SchemeFactory {
    public IndexEntryStandardScheme getScheme() {
      return new IndexEntryStandardScheme();
    }
  }

  private static class IndexEntryStandardScheme extends StandardScheme<IndexEntry> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IndexEntry struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // UNIQUE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.uniqueId = iprot.readString();
              struct.setUniqueIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VAULT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.vaultId = iprot.readString();
              struct.setVaultIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OWNER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ownerId = iprot.readString();
              struct.setOwnerIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TOKEN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.token = iprot.readString();
              struct.setTokenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // UPDATE_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.updateTimestamp = iprot.readI64();
              struct.setUpdateTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = IndexEntryStatus.findByValue(iprot.readI32());
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // ALTERNATE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.alternateId = iprot.readString();
              struct.setAlternateIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // ENTRY_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.entryData = iprot.readBinary();
              struct.setEntryDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 30: // META_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.metaData = new HashMap<String,String>(2*_map0.size);
                String _key1;
                String _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readString();
                  _val2 = iprot.readString();
                  struct.metaData.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setMetaDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 40: // CODEC_STRING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.codecString = iprot.readString();
              struct.setCodecStringIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 41: // DISPERSAL_ALGORITHM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dispersalAlgorithm = iprot.readString();
              struct.setDispersalAlgorithmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 42: // FRAGMENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fragmentId = iprot.readBinary();
              struct.setFragmentIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 43: // FRAGMENT_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.fragmentCount = iprot.readI16();
              struct.setFragmentCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 44: // STORAGE_NODE_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list4 = iprot.readListBegin();
                struct.storageNodeMap = new ArrayList<Integer>(_list4.size);
                int _elem5;
                for (int _i6 = 0; _i6 < _list4.size; ++_i6)
                {
                  _elem5 = iprot.readI32();
                  struct.storageNodeMap.add(_elem5);
                }
                iprot.readListEnd();
              }
              struct.setStorageNodeMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTimestamp()) {
        throw new TProtocolException("Required field 'timestamp' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetUpdateTimestamp()) {
        throw new TProtocolException("Required field 'updateTimestamp' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetFragmentCount()) {
        throw new TProtocolException("Required field 'fragmentCount' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IndexEntry struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.uniqueId != null) {
        oprot.writeFieldBegin(UNIQUE_ID_FIELD_DESC);
        oprot.writeString(struct.uniqueId);
        oprot.writeFieldEnd();
      }
      if (struct.vaultId != null) {
        oprot.writeFieldBegin(VAULT_ID_FIELD_DESC);
        oprot.writeString(struct.vaultId);
        oprot.writeFieldEnd();
      }
      if (struct.ownerId != null) {
        oprot.writeFieldBegin(OWNER_ID_FIELD_DESC);
        oprot.writeString(struct.ownerId);
        oprot.writeFieldEnd();
      }
      if (struct.token != null) {
        oprot.writeFieldBegin(TOKEN_FIELD_DESC);
        oprot.writeString(struct.token);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UPDATE_TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.updateTimestamp);
      oprot.writeFieldEnd();
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        oprot.writeI32(struct.status.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.alternateId != null) {
        if (struct.isSetAlternateId()) {
          oprot.writeFieldBegin(ALTERNATE_ID_FIELD_DESC);
          oprot.writeString(struct.alternateId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.entryData != null) {
        if (struct.isSetEntryData()) {
          oprot.writeFieldBegin(ENTRY_DATA_FIELD_DESC);
          oprot.writeBinary(struct.entryData);
          oprot.writeFieldEnd();
        }
      }
      if (struct.metaData != null) {
        if (struct.isSetMetaData()) {
          oprot.writeFieldBegin(META_DATA_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.metaData.size()));
            for (Map.Entry<String, String> _iter7 : struct.metaData.entrySet())
            {
              oprot.writeString(_iter7.getKey());
              oprot.writeString(_iter7.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.codecString != null) {
        oprot.writeFieldBegin(CODEC_STRING_FIELD_DESC);
        oprot.writeString(struct.codecString);
        oprot.writeFieldEnd();
      }
      if (struct.dispersalAlgorithm != null) {
        oprot.writeFieldBegin(DISPERSAL_ALGORITHM_FIELD_DESC);
        oprot.writeString(struct.dispersalAlgorithm);
        oprot.writeFieldEnd();
      }
      if (struct.fragmentId != null) {
        oprot.writeFieldBegin(FRAGMENT_ID_FIELD_DESC);
        oprot.writeBinary(struct.fragmentId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FRAGMENT_COUNT_FIELD_DESC);
      oprot.writeI16(struct.fragmentCount);
      oprot.writeFieldEnd();
      if (struct.storageNodeMap != null) {
        oprot.writeFieldBegin(STORAGE_NODE_MAP_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.storageNodeMap.size()));
          for (int _iter8 : struct.storageNodeMap)
          {
            oprot.writeI32(_iter8);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IndexEntryTupleSchemeFactory implements SchemeFactory {
    public IndexEntryTupleScheme getScheme() {
      return new IndexEntryTupleScheme();
    }
  }

  private static class IndexEntryTupleScheme extends TupleScheme<IndexEntry> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IndexEntry struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.uniqueId);
      oprot.writeString(struct.vaultId);
      oprot.writeString(struct.ownerId);
      oprot.writeString(struct.token);
      oprot.writeI64(struct.timestamp);
      oprot.writeI64(struct.updateTimestamp);
      oprot.writeI32(struct.status.getValue());
      oprot.writeString(struct.codecString);
      oprot.writeString(struct.dispersalAlgorithm);
      oprot.writeBinary(struct.fragmentId);
      oprot.writeI16(struct.fragmentCount);
      {
        oprot.writeI32(struct.storageNodeMap.size());
        for (int _iter9 : struct.storageNodeMap)
        {
          oprot.writeI32(_iter9);
        }
      }
      BitSet optionals = new BitSet();
      if (struct.isSetAlternateId()) {
        optionals.set(0);
      }
      if (struct.isSetEntryData()) {
        optionals.set(1);
      }
      if (struct.isSetMetaData()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetAlternateId()) {
        oprot.writeString(struct.alternateId);
      }
      if (struct.isSetEntryData()) {
        oprot.writeBinary(struct.entryData);
      }
      if (struct.isSetMetaData()) {
        {
          oprot.writeI32(struct.metaData.size());
          for (Map.Entry<String, String> _iter10 : struct.metaData.entrySet())
          {
            oprot.writeString(_iter10.getKey());
            oprot.writeString(_iter10.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IndexEntry struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.uniqueId = iprot.readString();
      struct.setUniqueIdIsSet(true);
      struct.vaultId = iprot.readString();
      struct.setVaultIdIsSet(true);
      struct.ownerId = iprot.readString();
      struct.setOwnerIdIsSet(true);
      struct.token = iprot.readString();
      struct.setTokenIsSet(true);
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
      struct.updateTimestamp = iprot.readI64();
      struct.setUpdateTimestampIsSet(true);
      struct.status = IndexEntryStatus.findByValue(iprot.readI32());
      struct.setStatusIsSet(true);
      struct.codecString = iprot.readString();
      struct.setCodecStringIsSet(true);
      struct.dispersalAlgorithm = iprot.readString();
      struct.setDispersalAlgorithmIsSet(true);
      struct.fragmentId = iprot.readBinary();
      struct.setFragmentIdIsSet(true);
      struct.fragmentCount = iprot.readI16();
      struct.setFragmentCountIsSet(true);
      {
        org.apache.thrift.protocol.TList _list11 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
        struct.storageNodeMap = new ArrayList<Integer>(_list11.size);
        int _elem12;
        for (int _i13 = 0; _i13 < _list11.size; ++_i13)
        {
          _elem12 = iprot.readI32();
          struct.storageNodeMap.add(_elem12);
        }
      }
      struct.setStorageNodeMapIsSet(true);
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.alternateId = iprot.readString();
        struct.setAlternateIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.entryData = iprot.readBinary();
        struct.setEntryDataIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TMap _map14 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.metaData = new HashMap<String,String>(2*_map14.size);
          String _key15;
          String _val16;
          for (int _i17 = 0; _i17 < _map14.size; ++_i17)
          {
            _key15 = iprot.readString();
            _val16 = iprot.readString();
            struct.metaData.put(_key15, _val16);
          }
        }
        struct.setMetaDataIsSet(true);
      }
    }
  }

}

